<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Authors>Niladri</Authors>
    <Company>NugetWorld</Company>
    <Copyright>Copyright (c) Niladri</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageProjectUrl>https://github.com/NiladriPadhy/Maui.NetworkMonitor</PackageProjectUrl>
    <RepositoryUrl>https://github.com/NiladriPadhy/Maui.NetworkMonitor</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>
</Project>
